### ISSUE TITLE
Please add a link for "Functional Programming of mHealth Applications"

### ISSUE THREAD

**Issue by mgorges** [gasche/icfp2013-papers#12]
A preprint for "Functional Programming of mHealth Applications" is available on Chris Petersen's website: http://ecem.ece.ubc.ca/~cpetersen/lambdanative_icfp13.pdf and the software development framework is available at https://github.com/part-cw/lambdanative

Thanks Matthias

**Comment by gasche** [comment]
I did just that, thanks for the links.
